Updating the Branding
kbuffardi/CodeWitUs pull request #26
Opened 2021-02-05 15:57 UTC by subhed

2021-02-05 17:00 UTC, kbuffardi commented
your changes are still overwriting the security patch. Please see https://github.com/kbuffardi/CodeWitUs/commit/c5595bd2232c4b6634c0084ce326abab20298c4e

2021-02-05 17:13 UTC, subhed commented
I have copied both the files from your commit and pasted

2021-02-05 18:25 UTC, kbuffardi commented on app/views/layouts/_header2.html.erb
> +                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
Most or all these changes in this file are reverting to an old version of the header, before it was corrected (to remove extraneous links and fix branding).

2021-02-05 18:26 UTC, kbuffardi commented on app/views/layouts/_header2.html.erb
> +        <%= button_to "Log In With Google", '/auth/google_oauth2',  {class: 'btn btn-small'}%>
Similarly, the security patch had changed this `button_to` to explicitly `post` but this reverts back to the older version.

2021-02-05 18:29 UTC, kbuffardi commented on app/views/layouts/_header.html.erb
> +            <li class="nav-item">
This file has the same problems as commented in _header2.html.erb

In addition, I'm not clear why we have two headers. If they're necessary, we should give them more descriptive names. If we don't need two, we should refactor to delete one and make sure we only use the other.

2021-02-05 18:36 UTC, kbuffardi requested changes
See the comments for specific problems that need to be fixed.

In the future, we need to make sure to take care to always pull from `primary` and merge into the feature branch. It will also help to isolate new features by creating independent branches for different features (e.g. `authentication`, `videos`, `creator`) one at a time and then make smaller pull requests that close individual issues (along with automating closing the issue with the commit message, when appropriate e.x. `Adds Foo feature, resolves #1`)

2021-02-05 18:39 UTC, subhed commented
Sure! Will follow that.

2021-02-08 19:22 UTC, merged

2021-02-11 17:55 UTC, kbuffardi commented
Resolves #23